from django.urls import path

from .views import (
    api_course_detail_json,
    api_courses_create,
    api_courses_delete,
    api_courses_list,
    api_courses_update,
    api_dashboard_create,
    api_dashboard_delete,
    api_dashboard_list,
    api_dashboard_stats,
    api_dashboard_update,
    api_enroll_student,
    api_export_courses,
    api_login,
    api_logout,
    api_student_detail,
    course_detail_api,
    courses_view,
    course_detail_view,
    dashboard_view,
    login_view,
    logout_view,
    student_detail_api,
    student_detail_view,
    update_course_website_api,
    student_search_api,
    enroll_student_view,
    api_export_students,
)


urlpatterns = [
    # HTML pages
    path("", login_view, name="login"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("dashboard/student-detail/", student_detail_api, name="student_detail_api"),
    path("dashboard/student/<int:student_id>/", student_detail_view, name="student_detail"),
    path("courses/", courses_view, name="courses"),
    path("courses/<int:course_id>/", course_detail_view, name="course_detail"),
    path("courses/course-detail/", course_detail_api, name="course_detail_api"),
    path("courses/update-website/", update_course_website_api, name="update_course_website_api"),
    path("courses/search-students/", student_search_api, name="student_search_api"),
    path("courses/enroll-student/", enroll_student_view, name="enroll_student"),
    path("logout/", logout_view, name="logout"),
    # API endpoints (JSON)
    path("api/login/", api_login, name="api_login"),
    path("api/logout/", api_logout, name="api_logout"),
    path("api/dashboard/", api_dashboard_list, name="api_dashboard_list"),
    path("api/dashboard/create/", api_dashboard_create, name="api_dashboard_create"),
    path("api/dashboard/<int:id>/", api_dashboard_update, name="api_dashboard_update"),
    path("api/dashboard/<int:id>/delete/", api_dashboard_delete, name="api_dashboard_delete"),
    path("api/dashboard/stats/", api_dashboard_stats, name="api_dashboard_stats"),
    path("api/students/<int:id>/", api_student_detail, name="api_student_detail"),
    path("api/students/export/", api_export_students, name="api_export_students"),
    path("api/courses/export/", api_export_courses, name="api_export_courses"),
    path("api/courses/", api_courses_list, name="api_courses_list"),
    path("api/courses/create/", api_courses_create, name="api_courses_create"),
    path("api/courses/<int:id>/", api_course_detail_json, name="api_course_detail_json"),
    path("api/courses/<int:id>/update/", api_courses_update, name="api_courses_update"),
    path("api/courses/<int:id>/delete/", api_courses_delete, name="api_courses_delete"),
    path("api/enroll/", api_enroll_student, name="api_enroll_student"),
]


