# Generated by Django 6.0.4 on 2026-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_course_and_customer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
