# Generated by Django 6.0.4 on 2026-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_customer_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='web_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
