# Generated by Django 6.0.4 on 2026-05-21 06:38

import django.db.models.deletion
from django.db import migrations, models


def copy_m2m_to_enrollment(apps, schema_editor):
    Customer = apps.get_model('botapp', 'Customer')
    Enrollment = apps.get_model('botapp', 'Enrollment')
    vendor = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        table_exists = False
        if vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='botapp_customer_courses'")
            table_exists = bool(cursor.fetchone())
        elif vendor == 'postgresql':
            cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'botapp_customer_courses')")
            table_exists = cursor.fetchone()[0]
            
        if table_exists:
            cursor.execute("SELECT customer_id, course_id FROM botapp_customer_courses")
            for customer_id, course_id in cursor.fetchall():
                customer = Customer.objects.filter(id=customer_id).first()
                if customer:
                    Enrollment.objects.get_or_create(
                        customer_id=customer_id,
                        course_id=course_id,
                        defaults={
                            "registration_date": customer.registration_date,
                            "expiry_date": customer.expiry_date,
                            "status": customer.status,
                        }
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_course_web_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='botapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='botapp.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='botapp.customer')),
            ],
        ),
        migrations.RunPython(copy_m2m_to_enrollment, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customer',
            name='courses',
        ),
        migrations.AddField(
            model_name='customer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='customers', through='botapp.Enrollment', to='botapp.course'),
        ),
    ]
