# Generated by Django 6.0.4 on 2026-05-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_courselink_enrollment_alter_customer_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='spotlight_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
