# Generated by Django 6.0.4 on 2026-05-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_course_spotlight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
