# Generated by Django 5.1.7 on 2026-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_sync_course_custom_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ChatGPT')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu đăng nhập')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255, verbose_name='IMAP Server')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP Port')),
                ('imap_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='IMAP Username')),
                ('imap_password', models.CharField(max_length=255, verbose_name='Mật khẩu ứng dụng Email (đọc OTP)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Khóa/Tạm dừng'), ('ERROR', 'Lỗi cấu hình mail')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
