# Generated by Django 5.1.7 on 2026-06-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0010_chatgptaccount_customer_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='spotlight_id',
        ),
    ]
