# Generated by Django 5.1.7 on 2026-06-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_remove_courses_add_chatgpt_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allowed_chatgpt_accounts',
            field=models.ManyToManyField(blank=True, related_name='allowed_customers', to='botapp.chatgptaccount', verbose_name='Tài khoản ChatGPT được cấp riêng'),
        ),
    ]
