# Generated by Django 5.1.7 on 2026-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_customer_allowed_chatgpt_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptaccount',
            name='is_visible_to_customers',
        ),
    ]
